### ISSUE TITLE
Problem with System.Configuration

### ISSUE THREAD

**Issue by stefan-toubia** [DocuWare/Platform.NETClient-Async-Samples#1]
When running the .NetCoreClientAsyncSamples project I had to add the Nuget package System.Configuration.ConfigurationManager to get things working.

**Comment by GranatenUdo** [comment]
Hi stoubia, thats odd because System.Configuration is not referenced anywhere. Which version of Visual Studio/MSBuild/dotnet did you use to build the project?

**Comment by stefan-toubia** [comment]
Hi obiwan, I'm on Visual Studio Community 2017, Windows 10 64 bit.  I'm using the .NET Standard 2.0.3 SDK, dotnet 2.1 installed.  I was getting this exception:

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

It's happening somewhere in the ServiceConnection.CreateAsync() call.
